### ISSUE TITLE
能不能把这个npm名称转给我啊？

### ISSUE THREAD

**Issue by i5ting** [switer/hostrc#1]
我写了一个proxy，也是用于切换host的，支持cli和api调用

**Comment by switer** [comment]
可以，我转给你，你账号多少？

**Comment by i5ting** [comment]
感谢，我的账号是i5ting，我会把感谢你加到文档，稍后我把开源地址发给你，欢迎pr和review

**Comment by switer** [comment]
npm上 owner 转给你了，麻烦确认下

**Comment by i5ting** [comment]
@switer 感谢，已经收到了

```
 npm owner ls hostrc
i5ting <shiren1118@126.com>
```

**Comment by i5ting** [comment]
@switer 再一次感谢，我把代码开源了，放在 https://github.com/i5ting/hostrc
